// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buku.proto

package buku;

public final class BukuOuterClass {
  private BukuOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BukuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buku.Buku)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id_buku = 1;</code>
     * @return The idBuku.
     */
    int getIdBuku();

    /**
     * <code>string judul = 2;</code>
     * @return The judul.
     */
    java.lang.String getJudul();
    /**
     * <code>string judul = 2;</code>
     * @return The bytes for judul.
     */
    com.google.protobuf.ByteString
        getJudulBytes();

    /**
     * <code>string penulis = 3;</code>
     * @return The penulis.
     */
    java.lang.String getPenulis();
    /**
     * <code>string penulis = 3;</code>
     * @return The bytes for penulis.
     */
    com.google.protobuf.ByteString
        getPenulisBytes();

    /**
     * <code>string penerbit = 4;</code>
     * @return The penerbit.
     */
    java.lang.String getPenerbit();
    /**
     * <code>string penerbit = 4;</code>
     * @return The bytes for penerbit.
     */
    com.google.protobuf.ByteString
        getPenerbitBytes();

    /**
     * <code>int32 tahun_terbit = 5;</code>
     * @return The tahunTerbit.
     */
    int getTahunTerbit();

    /**
     * <code>string harga = 6;</code>
     * @return The harga.
     */
    java.lang.String getHarga();
    /**
     * <code>string harga = 6;</code>
     * @return The bytes for harga.
     */
    com.google.protobuf.ByteString
        getHargaBytes();

    /**
     * <code>int32 stok = 7;</code>
     * @return The stok.
     */
    int getStok();
  }
  /**
   * Protobuf type {@code buku.Buku}
   */
  public static final class Buku extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buku.Buku)
      BukuOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Buku.newBuilder() to construct.
    private Buku(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Buku() {
      judul_ = "";
      penulis_ = "";
      penerbit_ = "";
      harga_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Buku();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buku.BukuOuterClass.internal_static_buku_Buku_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buku.BukuOuterClass.internal_static_buku_Buku_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buku.BukuOuterClass.Buku.class, buku.BukuOuterClass.Buku.Builder.class);
    }

    public static final int ID_BUKU_FIELD_NUMBER = 1;
    private int idBuku_ = 0;
    /**
     * <code>int32 id_buku = 1;</code>
     * @return The idBuku.
     */
    @java.lang.Override
    public int getIdBuku() {
      return idBuku_;
    }

    public static final int JUDUL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object judul_ = "";
    /**
     * <code>string judul = 2;</code>
     * @return The judul.
     */
    @java.lang.Override
    public java.lang.String getJudul() {
      java.lang.Object ref = judul_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        judul_ = s;
        return s;
      }
    }
    /**
     * <code>string judul = 2;</code>
     * @return The bytes for judul.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJudulBytes() {
      java.lang.Object ref = judul_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        judul_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PENULIS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object penulis_ = "";
    /**
     * <code>string penulis = 3;</code>
     * @return The penulis.
     */
    @java.lang.Override
    public java.lang.String getPenulis() {
      java.lang.Object ref = penulis_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        penulis_ = s;
        return s;
      }
    }
    /**
     * <code>string penulis = 3;</code>
     * @return The bytes for penulis.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPenulisBytes() {
      java.lang.Object ref = penulis_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        penulis_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PENERBIT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object penerbit_ = "";
    /**
     * <code>string penerbit = 4;</code>
     * @return The penerbit.
     */
    @java.lang.Override
    public java.lang.String getPenerbit() {
      java.lang.Object ref = penerbit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        penerbit_ = s;
        return s;
      }
    }
    /**
     * <code>string penerbit = 4;</code>
     * @return The bytes for penerbit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPenerbitBytes() {
      java.lang.Object ref = penerbit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        penerbit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAHUN_TERBIT_FIELD_NUMBER = 5;
    private int tahunTerbit_ = 0;
    /**
     * <code>int32 tahun_terbit = 5;</code>
     * @return The tahunTerbit.
     */
    @java.lang.Override
    public int getTahunTerbit() {
      return tahunTerbit_;
    }

    public static final int HARGA_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object harga_ = "";
    /**
     * <code>string harga = 6;</code>
     * @return The harga.
     */
    @java.lang.Override
    public java.lang.String getHarga() {
      java.lang.Object ref = harga_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        harga_ = s;
        return s;
      }
    }
    /**
     * <code>string harga = 6;</code>
     * @return The bytes for harga.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHargaBytes() {
      java.lang.Object ref = harga_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        harga_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOK_FIELD_NUMBER = 7;
    private int stok_ = 0;
    /**
     * <code>int32 stok = 7;</code>
     * @return The stok.
     */
    @java.lang.Override
    public int getStok() {
      return stok_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idBuku_ != 0) {
        output.writeInt32(1, idBuku_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(judul_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, judul_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(penulis_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, penulis_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(penerbit_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, penerbit_);
      }
      if (tahunTerbit_ != 0) {
        output.writeInt32(5, tahunTerbit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(harga_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, harga_);
      }
      if (stok_ != 0) {
        output.writeInt32(7, stok_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idBuku_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idBuku_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(judul_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, judul_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(penulis_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, penulis_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(penerbit_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, penerbit_);
      }
      if (tahunTerbit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, tahunTerbit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(harga_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, harga_);
      }
      if (stok_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, stok_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buku.BukuOuterClass.Buku)) {
        return super.equals(obj);
      }
      buku.BukuOuterClass.Buku other = (buku.BukuOuterClass.Buku) obj;

      if (getIdBuku()
          != other.getIdBuku()) return false;
      if (!getJudul()
          .equals(other.getJudul())) return false;
      if (!getPenulis()
          .equals(other.getPenulis())) return false;
      if (!getPenerbit()
          .equals(other.getPenerbit())) return false;
      if (getTahunTerbit()
          != other.getTahunTerbit()) return false;
      if (!getHarga()
          .equals(other.getHarga())) return false;
      if (getStok()
          != other.getStok()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_BUKU_FIELD_NUMBER;
      hash = (53 * hash) + getIdBuku();
      hash = (37 * hash) + JUDUL_FIELD_NUMBER;
      hash = (53 * hash) + getJudul().hashCode();
      hash = (37 * hash) + PENULIS_FIELD_NUMBER;
      hash = (53 * hash) + getPenulis().hashCode();
      hash = (37 * hash) + PENERBIT_FIELD_NUMBER;
      hash = (53 * hash) + getPenerbit().hashCode();
      hash = (37 * hash) + TAHUN_TERBIT_FIELD_NUMBER;
      hash = (53 * hash) + getTahunTerbit();
      hash = (37 * hash) + HARGA_FIELD_NUMBER;
      hash = (53 * hash) + getHarga().hashCode();
      hash = (37 * hash) + STOK_FIELD_NUMBER;
      hash = (53 * hash) + getStok();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buku.BukuOuterClass.Buku parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Buku parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Buku parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.Buku parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Buku parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Buku parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buku.BukuOuterClass.Buku prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buku.Buku}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buku.Buku)
        buku.BukuOuterClass.BukuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buku.BukuOuterClass.internal_static_buku_Buku_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buku.BukuOuterClass.internal_static_buku_Buku_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buku.BukuOuterClass.Buku.class, buku.BukuOuterClass.Buku.Builder.class);
      }

      // Construct using buku.BukuOuterClass.Buku.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idBuku_ = 0;
        judul_ = "";
        penulis_ = "";
        penerbit_ = "";
        tahunTerbit_ = 0;
        harga_ = "";
        stok_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buku.BukuOuterClass.internal_static_buku_Buku_descriptor;
      }

      @java.lang.Override
      public buku.BukuOuterClass.Buku getDefaultInstanceForType() {
        return buku.BukuOuterClass.Buku.getDefaultInstance();
      }

      @java.lang.Override
      public buku.BukuOuterClass.Buku build() {
        buku.BukuOuterClass.Buku result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buku.BukuOuterClass.Buku buildPartial() {
        buku.BukuOuterClass.Buku result = new buku.BukuOuterClass.Buku(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(buku.BukuOuterClass.Buku result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idBuku_ = idBuku_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.judul_ = judul_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.penulis_ = penulis_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.penerbit_ = penerbit_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tahunTerbit_ = tahunTerbit_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.harga_ = harga_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.stok_ = stok_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buku.BukuOuterClass.Buku) {
          return mergeFrom((buku.BukuOuterClass.Buku)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buku.BukuOuterClass.Buku other) {
        if (other == buku.BukuOuterClass.Buku.getDefaultInstance()) return this;
        if (other.getIdBuku() != 0) {
          setIdBuku(other.getIdBuku());
        }
        if (!other.getJudul().isEmpty()) {
          judul_ = other.judul_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPenulis().isEmpty()) {
          penulis_ = other.penulis_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPenerbit().isEmpty()) {
          penerbit_ = other.penerbit_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getTahunTerbit() != 0) {
          setTahunTerbit(other.getTahunTerbit());
        }
        if (!other.getHarga().isEmpty()) {
          harga_ = other.harga_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getStok() != 0) {
          setStok(other.getStok());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                idBuku_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                judul_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                penulis_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                penerbit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                tahunTerbit_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                harga_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                stok_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int idBuku_ ;
      /**
       * <code>int32 id_buku = 1;</code>
       * @return The idBuku.
       */
      @java.lang.Override
      public int getIdBuku() {
        return idBuku_;
      }
      /**
       * <code>int32 id_buku = 1;</code>
       * @param value The idBuku to set.
       * @return This builder for chaining.
       */
      public Builder setIdBuku(int value) {
        
        idBuku_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id_buku = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdBuku() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idBuku_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object judul_ = "";
      /**
       * <code>string judul = 2;</code>
       * @return The judul.
       */
      public java.lang.String getJudul() {
        java.lang.Object ref = judul_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          judul_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string judul = 2;</code>
       * @return The bytes for judul.
       */
      public com.google.protobuf.ByteString
          getJudulBytes() {
        java.lang.Object ref = judul_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          judul_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string judul = 2;</code>
       * @param value The judul to set.
       * @return This builder for chaining.
       */
      public Builder setJudul(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        judul_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string judul = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJudul() {
        judul_ = getDefaultInstance().getJudul();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string judul = 2;</code>
       * @param value The bytes for judul to set.
       * @return This builder for chaining.
       */
      public Builder setJudulBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        judul_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object penulis_ = "";
      /**
       * <code>string penulis = 3;</code>
       * @return The penulis.
       */
      public java.lang.String getPenulis() {
        java.lang.Object ref = penulis_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          penulis_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string penulis = 3;</code>
       * @return The bytes for penulis.
       */
      public com.google.protobuf.ByteString
          getPenulisBytes() {
        java.lang.Object ref = penulis_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          penulis_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string penulis = 3;</code>
       * @param value The penulis to set.
       * @return This builder for chaining.
       */
      public Builder setPenulis(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        penulis_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string penulis = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPenulis() {
        penulis_ = getDefaultInstance().getPenulis();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string penulis = 3;</code>
       * @param value The bytes for penulis to set.
       * @return This builder for chaining.
       */
      public Builder setPenulisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        penulis_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object penerbit_ = "";
      /**
       * <code>string penerbit = 4;</code>
       * @return The penerbit.
       */
      public java.lang.String getPenerbit() {
        java.lang.Object ref = penerbit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          penerbit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string penerbit = 4;</code>
       * @return The bytes for penerbit.
       */
      public com.google.protobuf.ByteString
          getPenerbitBytes() {
        java.lang.Object ref = penerbit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          penerbit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string penerbit = 4;</code>
       * @param value The penerbit to set.
       * @return This builder for chaining.
       */
      public Builder setPenerbit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        penerbit_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string penerbit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPenerbit() {
        penerbit_ = getDefaultInstance().getPenerbit();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string penerbit = 4;</code>
       * @param value The bytes for penerbit to set.
       * @return This builder for chaining.
       */
      public Builder setPenerbitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        penerbit_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int tahunTerbit_ ;
      /**
       * <code>int32 tahun_terbit = 5;</code>
       * @return The tahunTerbit.
       */
      @java.lang.Override
      public int getTahunTerbit() {
        return tahunTerbit_;
      }
      /**
       * <code>int32 tahun_terbit = 5;</code>
       * @param value The tahunTerbit to set.
       * @return This builder for chaining.
       */
      public Builder setTahunTerbit(int value) {
        
        tahunTerbit_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tahun_terbit = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTahunTerbit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tahunTerbit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object harga_ = "";
      /**
       * <code>string harga = 6;</code>
       * @return The harga.
       */
      public java.lang.String getHarga() {
        java.lang.Object ref = harga_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          harga_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string harga = 6;</code>
       * @return The bytes for harga.
       */
      public com.google.protobuf.ByteString
          getHargaBytes() {
        java.lang.Object ref = harga_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          harga_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string harga = 6;</code>
       * @param value The harga to set.
       * @return This builder for chaining.
       */
      public Builder setHarga(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        harga_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string harga = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHarga() {
        harga_ = getDefaultInstance().getHarga();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string harga = 6;</code>
       * @param value The bytes for harga to set.
       * @return This builder for chaining.
       */
      public Builder setHargaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        harga_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int stok_ ;
      /**
       * <code>int32 stok = 7;</code>
       * @return The stok.
       */
      @java.lang.Override
      public int getStok() {
        return stok_;
      }
      /**
       * <code>int32 stok = 7;</code>
       * @param value The stok to set.
       * @return This builder for chaining.
       */
      public Builder setStok(int value) {
        
        stok_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stok = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStok() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stok_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buku.Buku)
    }

    // @@protoc_insertion_point(class_scope:buku.Buku)
    private static final buku.BukuOuterClass.Buku DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buku.BukuOuterClass.Buku();
    }

    public static buku.BukuOuterClass.Buku getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Buku>
        PARSER = new com.google.protobuf.AbstractParser<Buku>() {
      @java.lang.Override
      public Buku parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Buku> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Buku> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buku.BukuOuterClass.Buku getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buku.IdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code buku.IdRequest}
   */
  public static final class IdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buku.IdRequest)
      IdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdRequest.newBuilder() to construct.
    private IdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buku.BukuOuterClass.internal_static_buku_IdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buku.BukuOuterClass.internal_static_buku_IdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buku.BukuOuterClass.IdRequest.class, buku.BukuOuterClass.IdRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buku.BukuOuterClass.IdRequest)) {
        return super.equals(obj);
      }
      buku.BukuOuterClass.IdRequest other = (buku.BukuOuterClass.IdRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buku.BukuOuterClass.IdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.IdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.IdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.IdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buku.BukuOuterClass.IdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buku.IdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buku.IdRequest)
        buku.BukuOuterClass.IdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buku.BukuOuterClass.internal_static_buku_IdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buku.BukuOuterClass.internal_static_buku_IdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buku.BukuOuterClass.IdRequest.class, buku.BukuOuterClass.IdRequest.Builder.class);
      }

      // Construct using buku.BukuOuterClass.IdRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buku.BukuOuterClass.internal_static_buku_IdRequest_descriptor;
      }

      @java.lang.Override
      public buku.BukuOuterClass.IdRequest getDefaultInstanceForType() {
        return buku.BukuOuterClass.IdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public buku.BukuOuterClass.IdRequest build() {
        buku.BukuOuterClass.IdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buku.BukuOuterClass.IdRequest buildPartial() {
        buku.BukuOuterClass.IdRequest result = new buku.BukuOuterClass.IdRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(buku.BukuOuterClass.IdRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buku.BukuOuterClass.IdRequest) {
          return mergeFrom((buku.BukuOuterClass.IdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buku.BukuOuterClass.IdRequest other) {
        if (other == buku.BukuOuterClass.IdRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buku.IdRequest)
    }

    // @@protoc_insertion_point(class_scope:buku.IdRequest)
    private static final buku.BukuOuterClass.IdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buku.BukuOuterClass.IdRequest();
    }

    public static buku.BukuOuterClass.IdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdRequest>
        PARSER = new com.google.protobuf.AbstractParser<IdRequest>() {
      @java.lang.Override
      public IdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buku.BukuOuterClass.IdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buku.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code buku.Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buku.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buku.BukuOuterClass.internal_static_buku_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buku.BukuOuterClass.internal_static_buku_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buku.BukuOuterClass.Empty.class, buku.BukuOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buku.BukuOuterClass.Empty)) {
        return super.equals(obj);
      }
      buku.BukuOuterClass.Empty other = (buku.BukuOuterClass.Empty) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buku.BukuOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buku.BukuOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buku.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buku.Empty)
        buku.BukuOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buku.BukuOuterClass.internal_static_buku_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buku.BukuOuterClass.internal_static_buku_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buku.BukuOuterClass.Empty.class, buku.BukuOuterClass.Empty.Builder.class);
      }

      // Construct using buku.BukuOuterClass.Empty.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buku.BukuOuterClass.internal_static_buku_Empty_descriptor;
      }

      @java.lang.Override
      public buku.BukuOuterClass.Empty getDefaultInstanceForType() {
        return buku.BukuOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public buku.BukuOuterClass.Empty build() {
        buku.BukuOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buku.BukuOuterClass.Empty buildPartial() {
        buku.BukuOuterClass.Empty result = new buku.BukuOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buku.BukuOuterClass.Empty) {
          return mergeFrom((buku.BukuOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buku.BukuOuterClass.Empty other) {
        if (other == buku.BukuOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buku.Empty)
    }

    // @@protoc_insertion_point(class_scope:buku.Empty)
    private static final buku.BukuOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buku.BukuOuterClass.Empty();
    }

    public static buku.BukuOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buku.BukuOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BukuListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buku.BukuList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    java.util.List<buku.BukuOuterClass.Buku> 
        getBukuList();
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    buku.BukuOuterClass.Buku getBuku(int index);
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    int getBukuCount();
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    java.util.List<? extends buku.BukuOuterClass.BukuOrBuilder> 
        getBukuOrBuilderList();
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    buku.BukuOuterClass.BukuOrBuilder getBukuOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code buku.BukuList}
   */
  public static final class BukuList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buku.BukuList)
      BukuListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BukuList.newBuilder() to construct.
    private BukuList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BukuList() {
      buku_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BukuList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buku.BukuOuterClass.internal_static_buku_BukuList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buku.BukuOuterClass.internal_static_buku_BukuList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buku.BukuOuterClass.BukuList.class, buku.BukuOuterClass.BukuList.Builder.class);
    }

    public static final int BUKU_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<buku.BukuOuterClass.Buku> buku_;
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    @java.lang.Override
    public java.util.List<buku.BukuOuterClass.Buku> getBukuList() {
      return buku_;
    }
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends buku.BukuOuterClass.BukuOrBuilder> 
        getBukuOrBuilderList() {
      return buku_;
    }
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    @java.lang.Override
    public int getBukuCount() {
      return buku_.size();
    }
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    @java.lang.Override
    public buku.BukuOuterClass.Buku getBuku(int index) {
      return buku_.get(index);
    }
    /**
     * <code>repeated .buku.Buku buku = 1;</code>
     */
    @java.lang.Override
    public buku.BukuOuterClass.BukuOrBuilder getBukuOrBuilder(
        int index) {
      return buku_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < buku_.size(); i++) {
        output.writeMessage(1, buku_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < buku_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buku_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buku.BukuOuterClass.BukuList)) {
        return super.equals(obj);
      }
      buku.BukuOuterClass.BukuList other = (buku.BukuOuterClass.BukuList) obj;

      if (!getBukuList()
          .equals(other.getBukuList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBukuCount() > 0) {
        hash = (37 * hash) + BUKU_FIELD_NUMBER;
        hash = (53 * hash) + getBukuList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buku.BukuOuterClass.BukuList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.BukuList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.BukuList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buku.BukuOuterClass.BukuList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buku.BukuOuterClass.BukuList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buku.BukuList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buku.BukuList)
        buku.BukuOuterClass.BukuListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buku.BukuOuterClass.internal_static_buku_BukuList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buku.BukuOuterClass.internal_static_buku_BukuList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buku.BukuOuterClass.BukuList.class, buku.BukuOuterClass.BukuList.Builder.class);
      }

      // Construct using buku.BukuOuterClass.BukuList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (bukuBuilder_ == null) {
          buku_ = java.util.Collections.emptyList();
        } else {
          buku_ = null;
          bukuBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buku.BukuOuterClass.internal_static_buku_BukuList_descriptor;
      }

      @java.lang.Override
      public buku.BukuOuterClass.BukuList getDefaultInstanceForType() {
        return buku.BukuOuterClass.BukuList.getDefaultInstance();
      }

      @java.lang.Override
      public buku.BukuOuterClass.BukuList build() {
        buku.BukuOuterClass.BukuList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public buku.BukuOuterClass.BukuList buildPartial() {
        buku.BukuOuterClass.BukuList result = new buku.BukuOuterClass.BukuList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(buku.BukuOuterClass.BukuList result) {
        if (bukuBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            buku_ = java.util.Collections.unmodifiableList(buku_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.buku_ = buku_;
        } else {
          result.buku_ = bukuBuilder_.build();
        }
      }

      private void buildPartial0(buku.BukuOuterClass.BukuList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buku.BukuOuterClass.BukuList) {
          return mergeFrom((buku.BukuOuterClass.BukuList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buku.BukuOuterClass.BukuList other) {
        if (other == buku.BukuOuterClass.BukuList.getDefaultInstance()) return this;
        if (bukuBuilder_ == null) {
          if (!other.buku_.isEmpty()) {
            if (buku_.isEmpty()) {
              buku_ = other.buku_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBukuIsMutable();
              buku_.addAll(other.buku_);
            }
            onChanged();
          }
        } else {
          if (!other.buku_.isEmpty()) {
            if (bukuBuilder_.isEmpty()) {
              bukuBuilder_.dispose();
              bukuBuilder_ = null;
              buku_ = other.buku_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bukuBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBukuFieldBuilder() : null;
            } else {
              bukuBuilder_.addAllMessages(other.buku_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                buku.BukuOuterClass.Buku m =
                    input.readMessage(
                        buku.BukuOuterClass.Buku.parser(),
                        extensionRegistry);
                if (bukuBuilder_ == null) {
                  ensureBukuIsMutable();
                  buku_.add(m);
                } else {
                  bukuBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<buku.BukuOuterClass.Buku> buku_ =
        java.util.Collections.emptyList();
      private void ensureBukuIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          buku_ = new java.util.ArrayList<buku.BukuOuterClass.Buku>(buku_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          buku.BukuOuterClass.Buku, buku.BukuOuterClass.Buku.Builder, buku.BukuOuterClass.BukuOrBuilder> bukuBuilder_;

      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public java.util.List<buku.BukuOuterClass.Buku> getBukuList() {
        if (bukuBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buku_);
        } else {
          return bukuBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public int getBukuCount() {
        if (bukuBuilder_ == null) {
          return buku_.size();
        } else {
          return bukuBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public buku.BukuOuterClass.Buku getBuku(int index) {
        if (bukuBuilder_ == null) {
          return buku_.get(index);
        } else {
          return bukuBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder setBuku(
          int index, buku.BukuOuterClass.Buku value) {
        if (bukuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBukuIsMutable();
          buku_.set(index, value);
          onChanged();
        } else {
          bukuBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder setBuku(
          int index, buku.BukuOuterClass.Buku.Builder builderForValue) {
        if (bukuBuilder_ == null) {
          ensureBukuIsMutable();
          buku_.set(index, builderForValue.build());
          onChanged();
        } else {
          bukuBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder addBuku(buku.BukuOuterClass.Buku value) {
        if (bukuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBukuIsMutable();
          buku_.add(value);
          onChanged();
        } else {
          bukuBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder addBuku(
          int index, buku.BukuOuterClass.Buku value) {
        if (bukuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBukuIsMutable();
          buku_.add(index, value);
          onChanged();
        } else {
          bukuBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder addBuku(
          buku.BukuOuterClass.Buku.Builder builderForValue) {
        if (bukuBuilder_ == null) {
          ensureBukuIsMutable();
          buku_.add(builderForValue.build());
          onChanged();
        } else {
          bukuBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder addBuku(
          int index, buku.BukuOuterClass.Buku.Builder builderForValue) {
        if (bukuBuilder_ == null) {
          ensureBukuIsMutable();
          buku_.add(index, builderForValue.build());
          onChanged();
        } else {
          bukuBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder addAllBuku(
          java.lang.Iterable<? extends buku.BukuOuterClass.Buku> values) {
        if (bukuBuilder_ == null) {
          ensureBukuIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, buku_);
          onChanged();
        } else {
          bukuBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder clearBuku() {
        if (bukuBuilder_ == null) {
          buku_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bukuBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public Builder removeBuku(int index) {
        if (bukuBuilder_ == null) {
          ensureBukuIsMutable();
          buku_.remove(index);
          onChanged();
        } else {
          bukuBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public buku.BukuOuterClass.Buku.Builder getBukuBuilder(
          int index) {
        return getBukuFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public buku.BukuOuterClass.BukuOrBuilder getBukuOrBuilder(
          int index) {
        if (bukuBuilder_ == null) {
          return buku_.get(index);  } else {
          return bukuBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public java.util.List<? extends buku.BukuOuterClass.BukuOrBuilder> 
           getBukuOrBuilderList() {
        if (bukuBuilder_ != null) {
          return bukuBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buku_);
        }
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public buku.BukuOuterClass.Buku.Builder addBukuBuilder() {
        return getBukuFieldBuilder().addBuilder(
            buku.BukuOuterClass.Buku.getDefaultInstance());
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public buku.BukuOuterClass.Buku.Builder addBukuBuilder(
          int index) {
        return getBukuFieldBuilder().addBuilder(
            index, buku.BukuOuterClass.Buku.getDefaultInstance());
      }
      /**
       * <code>repeated .buku.Buku buku = 1;</code>
       */
      public java.util.List<buku.BukuOuterClass.Buku.Builder> 
           getBukuBuilderList() {
        return getBukuFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          buku.BukuOuterClass.Buku, buku.BukuOuterClass.Buku.Builder, buku.BukuOuterClass.BukuOrBuilder> 
          getBukuFieldBuilder() {
        if (bukuBuilder_ == null) {
          bukuBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              buku.BukuOuterClass.Buku, buku.BukuOuterClass.Buku.Builder, buku.BukuOuterClass.BukuOrBuilder>(
                  buku_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          buku_ = null;
        }
        return bukuBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buku.BukuList)
    }

    // @@protoc_insertion_point(class_scope:buku.BukuList)
    private static final buku.BukuOuterClass.BukuList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buku.BukuOuterClass.BukuList();
    }

    public static buku.BukuOuterClass.BukuList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BukuList>
        PARSER = new com.google.protobuf.AbstractParser<BukuList>() {
      @java.lang.Override
      public BukuList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BukuList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BukuList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public buku.BukuOuterClass.BukuList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buku_Buku_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buku_Buku_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buku_IdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buku_IdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buku_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buku_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buku_BukuList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buku_BukuList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbuku.proto\022\004buku\"|\n\004Buku\022\017\n\007id_buku\030\001 " +
      "\001(\005\022\r\n\005judul\030\002 \001(\t\022\017\n\007penulis\030\003 \001(\t\022\020\n\010p" +
      "enerbit\030\004 \001(\t\022\024\n\014tahun_terbit\030\005 \001(\005\022\r\n\005h" +
      "arga\030\006 \001(\t\022\014\n\004stok\030\007 \001(\005\"\027\n\tIdRequest\022\n\n" +
      "\002id\030\001 \001(\005\"\007\n\005Empty\"$\n\010BukuList\022\030\n\004buku\030\001" +
      " \003(\0132\n.buku.Buku2\327\001\n\013BukuService\022$\n\nCrea" +
      "teBuku\022\n.buku.Buku\032\n.buku.Buku\022\'\n\010ReadBu" +
      "ku\022\017.buku.IdRequest\032\n.buku.Buku\022$\n\nUpdat" +
      "eBuku\022\n.buku.Buku\032\n.buku.Buku\022*\n\nDeleteB" +
      "uku\022\017.buku.IdRequest\032\013.buku.Empty\022\'\n\010Lis" +
      "tBuku\022\013.buku.Empty\032\016.buku.BukuListb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_buku_Buku_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buku_Buku_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buku_Buku_descriptor,
        new java.lang.String[] { "IdBuku", "Judul", "Penulis", "Penerbit", "TahunTerbit", "Harga", "Stok", });
    internal_static_buku_IdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_buku_IdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buku_IdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_buku_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_buku_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buku_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_buku_BukuList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_buku_BukuList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buku_BukuList_descriptor,
        new java.lang.String[] { "Buku", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
